global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["127.0.0.1:9000"]

  - job_name: twitter_api
    scrape_interval: 5s
    static_configs:
    - targets: ["api:8000"]
