{
 "title": "Twitter API",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total requests (by endpoint and status_code)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "starlette_requests_total" }
   ]
  },
  {
   "title": "Latency (in seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Amount of errors returned by path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "starlette_requests_total{status_code=~\"[45].*\"}"
    }
   ]
  },
  {
   "title": "Sum of all returned errors (aggregated by path)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(starlette_requests_total{status_code=~\"[45].*\"})"
    }
   ]
  }
 ]
}